-- SELECT UPDATED SWITZERLAND TABLE 
SELECT STREET_NUM ||' '|| STREET_NAME ||', '||TOWN_NAME||' '||CANTON_NAME AS "Address", LATITUDE ||',' ||LONGITUDE AS "Coordinates"
FROM SWITZERLAND
ORDER BY TOWN_NAME;

