-- CREATE TABLE TO LOAD .CSV DATA
CREATE TABLE SWITZERLAND 
(
LATITUDE VARCHAR2(200),
LONGITUDE VARCHAR2(200),
TOWN_NAME VARCHAR2(100),
STREET_NUM NUMBER,
STREET_NAME VARCHAR2(200)
);

-- CONFIRM STRUCTURE OF TABLE
SELECT * FROM SWITZERLAND;

-- OPEN TERMINAL IN ROOT CTL FOLDER
-- sqlldr control=out-all.ctl log=out-all.log
-- USERNAME: BRYAN/BRYAN

-- Table SWITZERLAND:
-- 56339 Rows successfully loaded.

-- CONFIRM ALL ROWS LOADED
SELECT * FROM SWITZERLAND;

-- COMMIT TO DB NOW THAT LOADING IS COMPLETE
COMMIT;
